### ISSUE TITLE
Rename is_uri_valid -> is_uri

### ISSUE THREAD

**Issue by daniel-qcode** [qcode-software/qcode-tcl#136]

**Comment by bvw** [comment]
Can mark the old name as deprecated and then in parallel change usage on any projects.

**Comment by bvw** [comment]
Actually Nicky has an ensemble for qc::cast and qc::is which might be relevant to this.

**Comment by daniel-qcode** [comment]
Cool, I'll take a look after I finish the conn_path stuff

On 14 January 2015 at 11:58, Bernhard van Woerden <notifications@github.com>
wrote:

> Actually Nicky has an ensemble for qc::cast and qc::is which might be
> relevant to this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qcode-software/qcode-tcl/issues/136#issuecomment-69906390>
> .
>



-- 
Kind Regards,
Daniel Clark
Qcode Software Limited
www.qcode.co.uk
Tel: +44(0) 1463 896 482

**Comment by daniel-qcode** [comment]
Asked Nicky to do this as he is working on is ensemble and docs just now

**Comment by bvw** [comment]
cool thanks.

**Comment by nicky-johnstone** [comment]
Pull request #143 now contains this change and documentation updated.

Deprecated:
`qc::is_uri_valid`

New:
`qc::is uri`

**Comment by nicky-johnstone** [comment]
Completed with merge of #143
