### ISSUE TITLE
Documentation & tests update for ensemble style qc::cast qc::castable and qc::is.

### ISSUE THREAD

**Issue by bvw** [qcode-software/qcode-tcl#141]

**Comment by nicky-johnstone** [comment]
The list of required documentation:

* Handlers ensemble
* Cast ensemble
* Castable ensemble
* Is ensemble
* Connection Handlers
  * handler_restful
  * handler_files
  * handler_db_files
* cast_values2model
* data_type_error_check
* form
* form_authenticity_token
* Registration
  * register 
  * validate
* Filters
  * filter_validate
  * filter_authenticate
  * filter_http_request_validate
  * filter_file_alias_paths
* file_alias_path_exists
* file_alias_path2file_id
* file_alias_path_new
* file_alias_path_update
* file_alias_path_delete
* filter_handler_exists

Documentation already started for filters and registration on branch [blog-project-shift-docs](https://github.com/qcode-software/qcode-tcl/tree/blog-project-shift-docs)

**Comment by bvw** [comment]
:+1:

**Comment by nicky-johnstone** [comment]
That's all of this documentation covered. A couple of things that haven't been covered in the documentation:

* User security (password verification and storage)
* Authenticity tokens

There might be a few more things that haven't been covered but they're not jumping out at me having reviewed the current documentation.

**Comment by bvw** [comment]
Those 2 would be good plus any higher level docs that tie pieces together.
