### ISSUE TITLE
qc::email_header_values failing on invalid Content-Type

### ISSUE THREAD

**Issue by davidqc** [qcode-software/qcode-tcl#145]
Email received with the following Content-Type which should not strictly have a trailing semicolon if it doesn't have parameters.

qc::email_header_values (rightly) assumes there will be more parameters after a semicolon and tries to split the empty string on "=" giving an error.

Should we check for the case where a parameter is {} and ignore it, or carry on failing with an error?

```
------=_NextPart_Avast_Info_Boundary
Content-Type: text/html;
Content-Transfer-Encoding: quoted-printable
Content-Description: avast info
```

```
proc qc::email_header_values {key value} {
    #| Convert header values to dict
    # Convert
    # Content-Type: multipart/report; report-type=delivery-status; boundary="=_ventus"
    # to dict
    # $key multipart/report report-type delivery-status boundary =_ventus
    set dict {}
    set list [split $value ";"]
    lappend dict $key [lindex $list 0]
    foreach part [lrange $list 1 end] {
	lassign [split_pair $part =] key value
	lappend dict $key [string trim $value \"']
    }
    return $dict
}
```

here:
key = Content-Type 
value = {text/html;}
%  set list [split $value ";"]
text/html {}

**Comment by bvw** [comment]
I think we should try to cope with this. How about a string trim right to remove the semi colon.

**Comment by davidqc** [comment]
https://github.com/qcode-software/qcode-tcl/pull/148

**Comment by davidqc** [comment]
https://github.com/qcode-software/qcode-tcl/pull/149 qcode-tcl-5
