### ISSUE TITLE
Document colon variable usage in registration.md

### ISSUE THREAD

**Issue by PeterChaplin** [qcode-software/qcode-tcl#169]
https://github.com/qcode-software/qcode-tcl/blob/master/doc/registration.md lacks documentation and examples of colon variables in url paths.

**Comment by nicky-johnstone** [comment]
It does indeed lack that information. Working on it just now as well as a few other smaller changes to the registration doc.

**Comment by nicky-johnstone** [comment]
It's been updated now. Hopefully the documentation is clear.
