### ISSUE TITLE
url_maker

### ISSUE THREAD

**Issue by bvw** [qcode-software/qcode-tcl#210]
Hi Peter

I'd like a little more syntactic sugar to make url construction more natural.
Could you please write a proc that will work as follows:-
```tcl
url_maker http://www.example.com :: 8000 / category $category edit ? filter foo # fragment
=> http://www.example.com::8000/category/123/edit?filter=foo#fragment

url_maker / category $category edit ? filter foo # fragment
=> /category/123/edit?filter=foo#fragment
```

I think in terms of implementation you can parse the list of arguments using `lsearch` etc and then build up a url dict data structure to pass to qc::url_make

**Comment by bvw** [comment]
Mmn thinking about this how would one distinguish between markers and values ?
Would user supplied values be able to force incorrect parsing ?

**Comment by PeterChaplin** [comment]
We could have:
```tcl
set id "?"
set name foo
set view grid
url_maker / category $id $name $view
=> /category?foo=grid
```
We could require that the arguments in must include `::`,`/`,`?`,`#`, which could give us:
```tcl
set group_name "sockets"
url_maker "" :: "" / ? # $group_name
=> "#sockets"
```
but that would still only allow us to error out when passed one of these symbols twice.

I'd be more in favour of using a bind-variable style syntax:
```
url_maker / category :category_id
```

**Comment by PeterChaplin** [comment]
Maybe with a symbol other than `:` to make parsing the `::` easier?

**Comment by bvw** [comment]
That could work but could also be limiting in that all the variables would have to be created in local scope first.
```
url_maker http://www.example.com :: 8000 / category :category edit ? filter foo # fragment
```
Can't do
```
url_maker http://www.example.com :: 8000 / category [get_category_id "Lamps"] edit ? filter foo # fragment
```

**Comment by PeterChaplin** [comment]
That's true. We could get around it by allowing something like:
```tcl
url_maker / category :{[get category_id]}
```
I don't know what you'd call that - a "bound statement"? But it does look pretty ugly to me.

I think that forcing developers to write
```tcl
set category_id [get_category_id "Lamps"]
url_maker / category :category_id
```
Might be acceptable - for the most part I'd find that style preferable anyway.

**Comment by PeterChaplin** [comment]
Or maybe we should try something like:
```tcl
url_maker {/ category [get_category_id "Lamps"] :category_name}
```
But that wouldn't make it obvious that "url_maker" is doing more than just straight-evaluating `[get_category_id "Lamps"]`. Maybe we could use an alternative syntax for marking up proc calls?

**Comment by PeterChaplin** [comment]
Thinking about it, maybe "bound statements" wouldn't be so bad, if we used a better syntax:
```tcl
url_maker / category :(get_category_id "Lamps") :category_name
```
It would potentially elevate the risks involved with writing bad code, though - if a developer wrote
```tcl
url_maker / category $category_name
```
then anyone able to modify category_name would be able to pass in code to be evaluated.

**Comment by bvw** [comment]
Okay could you look at writing an implementation that just did :variable substitution and lets see how that works please.

**Comment by PeterChaplin** [comment]
At present I have:
```tcl
url_maker https://qcode.co.uk/posts/321 / section 123
=> https://qcode.co.uk/section/123
```
it occurs to me that
```tcl
=> https://qcode.co.uk/posts/321/section/123
```
might be more useful.
What do you think?

**Comment by bvw** [comment]
yes that sounds okay.
