### ISSUE TITLE
qc::url support for colon variable substitution

### ISSUE THREAD

**Issue by bvw** [qcode-software/qcode-tcl#251]
Could we evolve qc::url so that colon variable substitution takes place on the url given using 
1. data from name/value pairs passed in as args
2. from the callers namespace.

Any name/value pairs not consumed by the template are inserted as GET string form variables.

Examples:
```tcl
qc::url https://www.qcode.co.uk::8000/foo/:foo_id/edit#:slug foo_id 12345 slug example-fragment foo bar baz 34

=> qc::url https://www.qcode.co.uk::8000/foo/12345/edit?foo=bar&baz=34#example-fragment
```

**Comment by nicky-johnstone** [comment]
Form vars will be a dictionary not a multimap.
```
qc::url http://www.qcode.co.uk?foo=bar foo baz
=> qc::url http://www.qcode.co.uk?foo=baz
```

**Comment by bvw** [comment]
@PeterChaplin Could you comment on this idea please.
My aspiration is to deprecate qc::url_maker in favour of this backward compatible implementation of qc::url without support for multimap form vars.

**Comment by PeterChaplin** [comment]
Looks ok to me. I'd be slightly concerned about having two different ways of passing  in data, but I can't think of any actual problems with it.

**Comment by PeterChaplin** [comment]
Is it worth having the extra complexity of picking up variable from the caller's namespace, if we're also allowing the user to pass in name/value pairs and/or use the `~` notation?

**Comment by bvw** [comment]
`~` parsing of args would be handy and an easy win if we use qc::args to parse.

Could not support caller namespace in the first version and see how we go.

**Comment by nicky-johnstone** [comment]
In testing the updated `qc::url` proc I came across this with `qc::url_parts`:

```
> qc::url_parts www.qcode.co.uk/post/new?title=foo&content=bar#title
base www.qcode.co.uk/post/new params {title foo content bar} hash title protocol {} domain {} port {} path www.qcode.co.uk/post/new segments {www.qcode.co.uk post new}
```

As can be seen it doesn't pull out the domain and instead treats it as part of the path whenever the scheme is missing.

According to the [URL spec](http://www.ietf.org/rfc/rfc1738.txt) it seems that the scheme is mandatory.

I'm not sure if we want to error out whenever a scheme is missing or make an assumption that no scheme specified defaults to `http`.

The updated definition of `qc::url` makes use of `qc::url_parts` and `qc::url_make` therefore it will be limited in the input that it can handle if this isn't changed but perhaps that's okay.

In essence, do we want to support:

```
> qc::url www.qcode.co.uk/post/new title foo content bar
http://www.qcode.co.uk/post/new?title=foo&content=bar
```

Or would we rather the scheme be specified by a user:

```
> qc::url http://www.qcode.co.uk/post/new title foo content bar
http://www.qcode.co.uk/post/new?title=foo&content=bar

> qc::url www.qcode.co.uk/post/new title foo content bar
No scheme specified.
```

I have no strong feelings either way.

**Comment by PeterChaplin** [comment]
Technically I believe:
`http://www.qcode.co.uk/www.somewhere-else.com/foo`
is a valid url.
Certainly, if you create a hyperlink as:
`<a href="www.somewhere-else.com/foo">Link</a>`
browsers will treat it as relative to the current page.

**Comment by nicky-johnstone** [comment]
Yeah, that's fine. My only concern was in cases where `qc::url` was already in use with domains that don't specify a scheme however I've been informed that this shouldn't be the case and therefore we should be okay to leave it as is.

**Comment by nicky-johnstone** [comment]
#255
