### ISSUE TITLE
Query string parsing

### ISSUE THREAD

**Issue by PeterChaplin** [qcode-software/qcode-tcl#263]
It seems that the following urls are valid per the specs:
```
https://www.mlaccessories.co.uk/home?test=foo
https://www.mlaccessories.co.uk/home?test
https://www.mlaccessories.co.uk/home?test&nothing
https://www.mlaccessories.co.uk/home?test&nothing=foo
https://www.mlaccessories.co.uk/home?test=foo&nothing
https://www.mlaccessories.co.uk/home?test=&nothing
https://www.mlaccessories.co.uk/home??
https://www.mlaccessories.co.uk/home?=
https://www.mlaccessories.co.uk/home?test&
```
I suspect several of these would cause problems with our existing procs, though. It shouldn't be a problem to have empty strings as keys or values, but I'm not sure if `?test` should be interpreted as `?test=` or `?=test`, or something else altogether.

@bvw any thoughts on how these should be handled?

**Comment by bvw** [comment]
I think we should define a subset of all legal urls with a more strict and limited definition to ensure that interpretation of form variables is unambiguous. 

ie example 2-9 above we would class as illegal for our purposes.

Any downsides that we know about to doing that ?

**Comment by PeterChaplin** [comment]
If a request comes in with a url in this form, it would be nice to serve it as a 404 instead of a generating a software error.
