### ISSUE TITLE
Prevent qc::form2vars setting any namespaced variables

### ISSUE THREAD

**Issue by daniel-qcode** [qcode-software/qcode-tcl#362]
If developer calls qc::form2vars without specifying any arguments is the query_string ```?::id=1``` the global variable id is set to 1.

##Acceptance Criteria 
qc::form2vars is not able to set any namespaced variables.

qcode-tcl 5 & 6 updated

**Comment by nicky-johnstone** [comment]
#365 #366

**Comment by daniel-qcode** [comment]
COMPLETE
