### ISSUE TITLE
Decide whether any of the following procs should be prevented from handling namespaced key/variable names ?

### ISSUE THREAD

**Issue by daniel-qcode** [qcode-software/qcode-tcl#363]
Decide whether any of the following procs should be prevented from setting/handling namespaced key/variable names ?

 * qc::form_var_names
 * qc::form2vars
 * qc::form_var_get
 * qc::form_var_exists
 * qc::form2dict
 * qc::form_proc
 * qc::args2vars
 * qc::dict2vars

Any others ?

I'm thinking at a minimum we should probably to qc::form2vars & qc::dict2vars (since this could be used in combination with qc::form2dict).
Think we need someone to access whether any changes are needed to the above qcode-tcl procs.

I think we should maybe get form2vars etc to raise an error instead of silently ignoring namespaced variable names.

**Comment by bvw** [comment]
Yes, all of the above should be restricted and they should raise an error if a variable name is namespace qualified.
In fact I think we could go further and limit form variable names to `[a-zA-Z0-9_-]`

**Comment by daniel-qcode** [comment]
Sounds good.

Agree that it would be good to limit variable names to [a-zA-Z0-9_-].

Might be good to log any variable names that do not match this regular expression for a week before enforcing this constraint. There might be other exotic variations that isn't covered by this regex that is in current use.

Otherwise we could rollout this change and we might break existing code.

**Comment by nicky-johnstone** [comment]
Would it be beneficial to create a filter to handle form variable name checking? With a filter the behaviour can be toggled for the whole project and it keeps the responsibilities of name checking out of the procedures mentioned in the original post.

**Comment by bvw** [comment]
Nicky, could you please create
1. A filter to notify us if a form variable breaks this regex
2. A pull request to enforce this restriction on the procs above and raise an error.

**Comment by nicky-johnstone** [comment]
Do we want the filter in qcode-tcl or just in each individual project?

```tcl
proc filter_invalid_form_variable_names {filter_when} {
    #| Filter that will send out an email when form variable names are invalid.
    #| Names are invalid if they contain any non-alphanumeric character that is
    #| not an underscore or hyphen.
    set names [ns_set_keys [ns_getform]]
    set failed [list]
    foreach name $names {
        if { [regexp {[^a-zA-Z0-9_-]} $name] } {
            lappend failed $name
        }
    }

    if { [llength $failed] > 0 } {
        set temp ""
        foreach name $failed {
            append temp [h li [qc::html_escape $name]]
        }
        set ul [h ul $temp]
        set content [h h2 "Invalid Form Variable Names"]
        
        set info [list]
        lappend info "[h strong "Hostname: "][ns_info hostname]"
        if { [qc::conn_open] } {
            lappend info "[h strong "URL: "][qc::html_escape [qc::conn_path]]"
            lappend info "[h strong "Request: "][qc::html_escape [ns_conn request]]"
        }
        lappend info "[h strong "Time: "][qc::format_timestamp now]"
        
        append content [h p [join $info [h br]]]
        append content [h p "The following form variable names have invalid characters:"]
        append content $ul
        set html [h html [h body $content]]
        
        qc::email_support \
            subject "Invalid Form Variable Names" \
            html $html
    }
    
    return "filter_ok"
}
```

Tested it out by adding an invalid form variable to a request:
![image](https://cloud.githubusercontent.com/assets/8330836/14859517/62d43c7e-0c9c-11e6-8156-8635ca29aba9.png)

**Comment by bvw** [comment]
We can apply this filter in each project.

**Comment by daniel-qcode** [comment]
@bvw Do you think this filter is still required ... might be ok to just rollback if there are problems ?

**Comment by bvw** [comment]
A filter like this might develop into a web application firewall where we run some sanity checks against requests in the same way as we have a filter for url correctness.
A penetration test would then receive an HTTP response code to indicate an invalid request rather than triggering a hard error in our application code.

**Comment by daniel-qcode** [comment]
COMPLETE
