### ISSUE TITLE
Filter to check form variable names do not contain ::

### ISSUE THREAD

**Issue by daniel-qcode** [qcode-software/qcode-tcl#369]
Extend ```qc::filter_http_request_validate``` to validate form variable names

In the first instance we should just write to the log file when we find a form_variable names that contains ```::```.

After monitoring log files for a few days we can modify this to return a 400 Bad Request response if this is appropriate.

## Acceptance Criteria
```qc::filter_http_request_validate``` filter has been updated (and backported to qcode-tcl-5)

**Comment by nicky-johnstone** [comment]
On the mla-erp project:
* Filters except `qc::filter_http_request_validate`: ~200ms
* Including `qc::filter_http_request_validate`: ~430ms

**Comment by nicky-johnstone** [comment]
I suspect the previous timings weren't accurate. After retesting `qc::filter_http_request_validate` here are the results:

Case | Time
-------|-------
No form vars | ~17ms
1 valid form var | ~17ms
1 invalid form var | ~19ms
10 valid form vars | ~17ms
10 invalid form vars | ~18ms

**Comment by nicky-johnstone** [comment]
Timing the individual components where possible:

```
> time [list qc::is::uri "/test"] 100
55.33 microseconds per iteration

> time [list qc::conn_request_is_valid "GET /test?hello::world=foo HTTP/1.1"] 100
49.27 microseconds per iteration
```

```
proc qc::filter_http_request_validate {event args} {
    ...
    set t1 [clock milliseconds]
    set names [qc::form_var_names]
    set t2 [clock milliseconds]
    log "form_var_name took [expr {$t2 - $t1}] ms"
    ...
}

> form_var_names took 0 ms
```

**Comment by nicky-johnstone** [comment]
First time executing each after a restart:
```
> time [list qc::is::uri "/test"]
264975 microseconds per iteration

> time [list qc::conn_is_request_valid "GET /test?hello:::world=foo HTTP/1.1"]
3478 microseconds per iteration
```

**Comment by nicky-johnstone** [comment]
```tcl
proc qc::filter_form_variables {event args} {
    #|
    qc::args $args -log -error_handler "qc::error_handler" --

    ::try {
        # Check form variable names to prevent Tcl namespaced variables from
        # being set or overwritten.
        set names [qc::form_var_names]
        foreach name $names {
            if { [regexp {::} $name] } {
                ns_returnbadrequest "Invalid form variable name: \"$name\""
                
                if { [info exists log] } {
                    set request [ns_conn request]
                    log "qc::filter_http_request_validate:\
                         Invalid Form Variable Name: \"$name\"\
                         for request \"$request\""
                    qc::email_support \
                        subject "Invalid HTTP Request" \
                        html "Invalid request \"[qc::html_escape $request]\""
                }
                
                return filter_return
            }
        }
        
        return filter_ok
    } on error {error_message options} {
        $error_handler $error_message [dict get $options -errorinfo] \
            [dict get $options -errorcode]
        return filter_return
    }
}
```

## No form vars

Case | Time
-------|-------
Without filter | 195ms
With filter | 195ms

## 1 invalid form var

Case | Time
-------|-------
Without filter |195ms
With filter | 345ms 

## 10 valid form vars

Case | Time
-------|-------
Without filter | 195ms
With filter | 195ms

## 10 invalid form vars

Case | Time
-------|-------
Without filter | 195ms
With filter | 350ms

---

Where form variables are valid the increase is negligible. Where there are invalid form variables it takes about 350ms which is due to logging. With 10 invalid form variables but without the `-log` flag the filters only take 1ms.

**Comment by daniel-qcode** [comment]
COMPLETE
