### ISSUE TITLE
qc::form2dict – Set form variable array names without the square brackets

### ISSUE THREAD

**Issue by nicky-johnstone** [qcode-software/qcode-tcl#383]
When not explicitly passing arguments to `qc::form2dict` it leaves the square brackets in the form var name. E.g.

Form data
```
purchase_order_id[]: 12345
purchase_order_id[]: 67890
```

```
puts [qc::form2dict]
{purchase_order_id[]} {12345 67890} {purchase_order_id[]} {12345 67890}
```

Expected output:
```
puts [qc::form2dict]
purchase_order_id {12345 67890}
```

**Acceptance Criteria:** Form variable array names are combined and set in the dict without the square brackets.

**Comment by daniel-qcode** [comment]
@nicky-johnstone can this be closed ?
